type: 'b2a'
regression:
    degree: 2
    alpha: 0.0
network:
    type: 'polynomial'
    polynomial:
        alpha: 0.0
output_dir: 'output'
ds_gender: 'female'
model_gender: 'female'
model_type: 'smplx'
num_shape_comps: 10

dataset:
    -   'caesar'
    
use_attributes: True
use_measurements: False 